<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/library/bootstrap/4.0/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/library/bootstrap/4.0/bootstrap-grid.min.css'))
            ->prependStylesheet($this->basePath('css/library/datatables/datatables.min.css'))
            ->appendStylesheet($this->basePath('css/library/bootstrap/datepicker/bootstrap-datepicker3.min.css'))
            ->appendStylesheet($this->basePath('css/library/bootstrap/datepicker/bootstrap-datepicker3.standalone.min'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/library/bootstrap/datepicker/bootstrap-datepicker.min.js'))
            ->prependFile($this->basePath('js/library/datatables/datatables.min.js'))
            ->prependFile($this->basePath('js/library/bootstrap/4.0/bootstrap.min.js'))
            ->prependFile($this->basePath('js/library/popper/popper.min.js'))
            ->prependFile($this->basePath('js/library/jquery/jquery-ui.min.js'))
            ->prependFile($this->basePath('js/library/jquery/jquery-3.1.0.min.js'))

        ?>
    </head>
    <body>

    <!-- Navigation bar -->
    <?php
    // Check if the activeMenuItemId passed to layout view model
    // and if so, use it for setting active navbar item.
    if (isset($activeMenuItemId)) {
        $this->mainMenu()->setActiveItemId($activeMenuItemId);
    }

    // Render the navbar
    echo $this->mainMenu()->render();
    ?>
    <div class="container">
        <?= $this->content ?>
        <hr>
        <footer>
            <p>&copy;Buu corporation</p>

            <small>
                <div>Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a>
                    from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>
                    is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a>
                </div>
            </small>
        </footer>
    </div>
    <?= $this->inlineScript() ?>
    </body>
</html>