<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/library/bootstrap/4.0/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/library/bootstrap/4.0/bootstrap-grid.min.css'))
            ->prependStylesheet($this->basePath('css/library/datatables/datatables.min.css'))
            ->appendStylesheet($this->basePath('css/library/bootstrap/datepicker/bootstrap-datepicker3.min.css'))
            ->appendStylesheet($this->basePath('css/library/bootstrap/datepicker/bootstrap-datepicker3.standalone.min'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->appendFile($this->basePath('js/library/jquery/jquery-3.1.0.min.js'))
            ->appendFile($this->basePath('js/library/popper/popper.min.js'))
            ->appendFile($this->basePath('js/library/bootstrap/4.0/bootstrap.min.js'))
            ->appendFile($this->basePath('js/library/datatables/datatables.min.js'))
            ->appendFile($this->basePath('js/library/bootstrap/datepicker/bootstrap-datepicker.min.js'))

        ?>
    </head>
    <body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark  bg-primary ">
        <a class="navbar-brand" href="<?= $this->url('home') ?>">Finance</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <?php
                $menu = [
                    'home' => 'Dashboard',
                    'transaction' => 'Transactions',
                    'cashflow' => 'CashFlow',
                    'keywords' => 'Keywords',
                    'import' => 'Import',
                ];
                $currentUrl = $this->url();
                ?>
                <?php foreach ($menu as $link => $title) : ?>
                    <li class="nav-item <?= $currentUrl == $this->url($link) ? 'active' : ''?>">
                        <a class="nav-link" href="<?= $this->url($link) ?>"><?= $title; ?></a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </nav>
    <div class="container">
        <?= $this->content ?>
        <hr>
        <footer>
            <p>&copy;Buu corporation</p>
        </footer>
    </div>
    <?= $this->inlineScript() ?>
    </body>
</html>