<nav class="navbar fixed-top navbar-expand-lg navbar-dark  bg-primary ">
    <a class="navbar-brand" href="<?= $this->url('home') ?>">Finance</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <!-- left-justified items -->
            <?php foreach ($this->items as $item): ?>
                <?php if (!empty($item['float']) && $item['float'] == 'right') {
                    continue;
                }
                ?>
                <?= $this->render('layout/nav-item.phtml', ['item' => $item]); ?>
            <?php endforeach; ?>
        </ul>

        <ul class="navbar-nav navbar-right">
            <!-- right-justified items -->
            <?php foreach ($this->items as $item): ?>
                <?php if (empty($item['float']) || $item['float'] != 'right') {
                    continue;
                }
                ?>
                <?= $this->render('layout/nav-item.phtml', ['item' => $item]); ?>
            <?php endforeach; ?>
        </ul>
    </div>
</nav>