<?php $this->headScript()->appendFile($this->basePath('js/view/transaction/FinTransactions.js'));?>

<div class="jumbotron bg-light pt-0" >
    <form id="filter_form" class="pt-4">
        <div class="form-group row bg-warning text-white pl-3 rounded">
            <div class="col-sm-2 p-1">
                <label for="date_from">Date From</label>
                <input class="form-control datepicker" id="date_from" type="text" value="<?= $this->dateFrom;?>">
            </div>
            <div class="col-sm-2 p-1">
                <label for="date_to">Date To</label>
                <input class="form-control datepicker" id="date_to" type="text" value="<?= $this->dateTo;?>">
            </div>
            <div class="col-sm-2 p-1">
                <label for="account_id">Account</label>
                <select class="form-control" id="account_id">
                    <?php foreach ($this->accounts as $accountId => $accountName) : ?>
                        <option value="<?= $accountId; ?>"><?= $accountName;?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="col-sm-2 p-1">
                <label for="category_id">Category</label>
                <select class="form-control" id="category_id">
                    <?php foreach ($this->categories as $categoryId => $categoryName) : ?>
                        <option value="<?= $categoryId; ?>" <?=$this->categoryId == $categoryId ? 'selected' : ''?>><?= $categoryName;?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="col-sm-3 p-1">
                <label for="description">Description</label>
                <input class="form-control" id="description" type="text">
            </div>
            <div class="col-sm-1 p-1">
                <label for="">&nbsp;</label><br/>
                <button id="reload" type="button" class="btn btn-secondary mb-2" onclick="doTableReload()">Filter</button>
            </div>
        </div>
    </form>

	<form id="transaction_form">
		<div class="form-group row bg-primary text-white pl-3 pt-3 pb-3 rounded">
			<div class="col-sm-2 p-1">
				<label for="category_id">Set Category</label>
            </div>
            <div class="col-sm-3 p-1">
				<select class="form-control" id="new_category_id" name="new_category_id">
					<?php foreach ($this->categories as $categoryId => $categoryName) : ?>
						<option value="<?= $categoryId; ?>"><?= $categoryName;?></option>
					<?php endforeach; ?>
				</select>
			</div>
			<div class="col-sm-2 p-1">
				<button id="apply" type="button" class="btn btn-outline-light" onclick="applyChanges()">Apply</button>
			</div>
			
		</div>
		<table id="transactions" class="display" width="100%"></table>
        <div class="col-sm-4">
            <label for="description">Total: <span id="transaction_total"></span></label>
        </div>
	</form>
</div>

<script>
    doTableReload = function() {
        FinTransactions.reload();
    };
    applyChanges = function() {
        FinTransactions.applyChanges();
    };

    $(document).ready(function() {
        $('.datepicker').datepicker({
            format: 'mm/dd/yyyy'
        });

        FinTransactions.init({
            url: '/transaction/load',
            saveUrl: '/transaction/save',
            table: $('#transactions'),
            filterForm: $('#filter_form'),
			form: $('#transaction_form'),
        })
    } );
</script>