<?php $this->headScript()->appendFile($this->basePath('js/widget/pocketMoney.js'));?>
<?php $this->headScript()->appendFile($this->basePath('js/widget/wCashFlow.js'));?>

<div class="row">
    <div class="col-sm-4">
        <div id="widget_pocket_money" class="card bg-light mb-3 mt-3"  ></div>
    </div>
    <div class="col-sm-8">
        <div id="widget_cashflow" class="card bg-light mb-3 mt-3" ></div>
    </div>
</div>


<script>
    PocketMoney.init({
        url: '/transaction/pocket',
        container: $('#widget_pocket_money')
    });

    wCashFlow.init({
        url: '/cashflow/get',
        container: $('#widget_cashflow')
    })
</script>