<?= $this->headScript()
    ->appendFile($this->basePath('js/library/chart/Chart.min.js'));
?>

<div class="jumbotron bg-light pt-0" >
    <form id="transaction_form">
        <div class="form-group row bg-warning text-white pl-3 rounded">
            <div class="col-sm-2 p-1">
            </div>
            <div class="col-sm-2 p-1">
                <select class="form-control" id="new_category_id" name="new_category_id">
                    <?php foreach ($this->periods as $ym => $name) : ?>
                        <option value="<?= $ym; ?>" <?= $this->fromMonth == $ym ? ' selected' : '';?>><?= $name;?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="col-sm-3 p-1">
                <select class="form-control" id="new_category_id" name="new_category_id">
                    <?php foreach ($this->categories as $categoryId => $categoryName) : ?>
                        <option value="<?= $categoryId; ?>"><?= $categoryName;?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="col-sm-2 p-1">
                <select class="form-control" id="new_category_id" name="new_category_id">
                    <?php foreach ($this->periods as $ym => $name) : ?>
                        <option value="<?= $ym; ?>" <?= $this->toMonth == $ym ? ' selected' : '';?>><?= $name;?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="col-sm-11 pl-5">
            <canvas id="canvas"></canvas>
        </div>
    </form>
</div>





<script>
    window.randomScalingFactor = function() {
        return Math.round(200) - 100;
    };

    var chartColors = {
        red: 'rgb(255, 99, 132)',
        orange: 'rgb(255, 159, 64)',
        yellow: 'rgb(255, 205, 86)',
        green: 'rgb(75, 192, 192)',
        blue: 'rgb(54, 162, 235)',
        purple: 'rgb(153, 102, 255)',
        grey: 'rgb(201, 203, 207)'
    };
    var MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
    var config = {
        type: 'line',
        data: {
            labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
            datasets: [{
                label: 'My First dataset',
                backgroundColor: chartColors.red,
                borderColor: chartColors.red,
                data: [
                    100,
                    230.24,
                    54.56,
                    -234,
                    0,
                    6,
                    7
                ],
                fill: false,
            }, {
                label: 'My Second dataset',
                fill: false,
                backgroundColor: chartColors.blue,
                borderColor: chartColors.blue,
                data: [
                    7,
                    6,
                    5,
                    4,
                    3,
                    2,
                    1
                ],
            }]
        },
        options: {
            responsive: true,
            title: {
                display: true,
                text: 'Cash Flow Chart'
            },
            tooltips: {
                mode: 'index',
                intersect: false,
            },
            hover: {
                mode: 'nearest',
                intersect: true
            },
            scales: {
                xAxes: [{
                    display: true,
                    scaleLabel: {
                        display: true,
                        labelString: 'Month'
                    }
                }],
                yAxes: [{
                    display: true,
                    scaleLabel: {
                        display: true,
                        labelString: 'Value'
                    }
                }]
            }
        }
    };

    window.onload = function() {
        var ctx = document.getElementById('canvas').getContext('2d');
        window.myLine = new Chart(ctx, config);
    };

    document.getElementById('randomizeData').addEventListener('click', function() {
        config.data.datasets.forEach(function(dataset) {
            dataset.data = dataset.data.map(function() {
                return randomScalingFactor();
            });

        });

        window.myLine.update();
    });

    var colorNames = Object.keys(chartColors);
    // document.getElementById('addDataset').addEventListener('click', function() {
    //     var colorName = colorNames[config.data.datasets.length % colorNames.length];
    //     var newColor = chartColors[colorName];
    //     var newDataset = {
    //         label: 'Dataset ' + config.data.datasets.length,
    //         backgroundColor: newColor,
    //         borderColor: newColor,
    //         data: [],
    //         fill: false
    //     };
    //
    //     for (var index = 0; index < config.data.labels.length; ++index) {
    //         newDataset.data.push(randomScalingFactor());
    //     }
    //
    //     config.data.datasets.push(newDataset);
    //     window.myLine.update();
    // });
    //
    // document.getElementById('addData').addEventListener('click', function() {
    //     if (config.data.datasets.length > 0) {
    //         var month = MONTHS[config.data.labels.length % MONTHS.length];
    //         config.data.labels.push(month);
    //
    //         config.data.datasets.forEach(function(dataset) {
    //             dataset.data.push(randomScalingFactor());
    //         });
    //
    //         window.myLine.update();
    //     }
    // });
    //
    // document.getElementById('removeDataset').addEventListener('click', function() {
    //     config.data.datasets.splice(0, 1);
    //     window.myLine.update();
    // });
    //
    // document.getElementById('removeData').addEventListener('click', function() {
    //     config.data.labels.splice(-1, 1); // remove the label first
    //
    //     config.data.datasets.forEach(function(dataset) {
    //         dataset.data.pop();
    //     });
    //
    //     window.myLine.update();
    // });
</script>