<?php $this->headScript()->appendFile($this->basePath('js/view/budget/FinBudget.js'));?>

<!-- top navigation -->
<div class="row justify-content-center">
    <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
        <div class="btn-group" role="group">
            <button id="current-year" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <?= $this->selectedYear; ?>
            </button>
            <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                <?php foreach ($this->years as $year) : ?>
                    <a class="dropdown-item" href="javascript:void(0)" onclick="FinCashflow.selectYear($('#current-year'), '<?= $year; ?>')"><?= $year; ?></a>
                <?php endforeach; ?>
            </div>
        </div>

        <?php foreach ($this->months as $monthDigit => $monthName): ?>
            <button type="button" class="btn period-month <?= $monthDigit == $this->selectedMonth ? 'btn-primary' : 'btn-secondary'?>"
                    onclick="FinCashflow.selectMonth(this, '<?=sprintf('%02d', $monthDigit );?>')">
                <?= $monthName; ?>
            </button>
        <?php endforeach; ?>
    </div>
</div>

<div id="month-budget">
    <?= $this->partial('application/budget/content.phtml', ['data' => $this->data]); ?>
</div>