<div id="accordion" class="mt-5">
    <div class="card">
        <div class="card-header p-1" id="headingOne">
            <h5 class="mb-0">
                <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    Unbudgeted
                    <span class="badge badge-primary">3</span>
                </button>
            </h5>
        </div>
        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
            <div class="card-body">

                <ul class="list-group">
                    <li class="list-group-item list-group-item-light list-group-item-action ">
                        Category 1  Name ( $123.34)
                        <button type="button" class="btn btn-outline-info btn-sm float-right " data-toggle="modal" data-target="#category1Budget">
                            Create Budget
                        </button>
                    </li>
                    <li class="list-group-item list-group-item-light list-group-item-action ">
                        Category 2 Name ( $123.34)
                        <button type="button" class="btn btn-outline-info btn-sm float-right " data-toggle="modal" data-target="#category2Budget">
                            Create Budget
                        </button>
                    </li>
                    <li class="list-group-item list-group-item-light list-group-item-action ">
                        Category 3 Name ( $123.34)
                        <button type="button" class="btn btn-outline-info btn-sm float-right " data-toggle="modal" data-target="#category3Budget">
                            Create Budget
                        </button>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<?php // @TODO load modal window when clicked on a button ?>

<?= $this->partial('application/budget/edit-budget-modal.phtml', [
    'modalId'=> 'category1Budget',
    'title' => 'Category 1. Create Budget',
    'dateFrom' => '2018-03-01',
    'dateTo' => '2018-03-31',
]); ?>


<?= $this->partial('application/budget/edit-budget-modal.phtml', [
    'modalId'=> 'category2Budget',
    'title' => 'Category 2. Create Budget',
    'dateFrom' => '2018-03-01',
    'dateTo' => '2018-03-31',
]); ?>

<?= $this->partial('application/budget/edit-budget-modal.phtml', [
    'modalId'=> 'category3Budget',
    'title' => 'Category 3. Create Budget',
    'dateFrom' => '2018-03-01',
    'dateTo' => '2018-03-31',
]); ?>
